language: c
sudo: required
install: sh -e install-deps.sh
script: make check
notifications:
  email: lars@nocrew.org
  irc:
    channels: irc.nocrew.org#nocrew
    template: ${repository} ${branch} ${message}
    use_notice: true
    skip_join: true
